# Generated by Django 3.0.3 on 2020-03-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patiententry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=5, verbose_name='Patient ID')),
                ('predicted_age', models.CharField(max_length=50, verbose_name='Predicted Age')),
                ('predicted_sex', models.CharField(max_length=50, verbose_name='Predicted Sex')),
                ('predicted_premature', models.CharField(max_length=200, verbose_name='Predicted Premature')),
                ('segmented_address', models.CharField(max_length=200)),
            ],
        ),
    ]
