# Generated by Django 3.0.3 on 2020-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patientresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100, verbose_name='participant_id')),
                ('session_id', models.CharField(max_length=100, verbose_name='session_id')),
                ('gender', models.CharField(max_length=100, verbose_name='gender')),
                ('birth_age', models.CharField(max_length=100, verbose_name='birth_age')),
                ('birth_weight', models.CharField(max_length=100, verbose_name='birth_weight')),
                ('singleton', models.CharField(max_length=100, verbose_name='singleton')),
                ('scan_age', models.CharField(max_length=50, verbose_name='scan_age')),
                ('scan_number', models.CharField(max_length=50, verbose_name='scan_number')),
                ('radiology_score', models.CharField(max_length=200, verbose_name='radiology_score')),
                ('sedation', models.CharField(max_length=200, verbose_name='sedation')),
            ],
        ),
    ]
