# Generated by Django 3.0.3 on 2020-03-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_patientdatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdatabase',
            old_name='pid',
            new_name='participant_id',
        ),
    ]
