# Generated by Django 3.0.3 on 2020-03-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200330_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientResults',
            new_name='PatientResult',
        ),
        migrations.AlterModelOptions(
            name='patientdatabase',
            options={'verbose_name_plural': 'Patient Database'},
        ),
        migrations.AlterModelOptions(
            name='patiententry',
            options={'verbose_name_plural': 'Patient Entries'},
        ),
        migrations.AlterModelOptions(
            name='patientresult',
            options={'verbose_name_plural': 'Patient Results'},
        ),
    ]
