# Generated by Django 3.0.3 on 2020-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200330_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, verbose_name='session_id')),
            ],
        ),
        migrations.CreateModel(
            name='GreyMatterVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, verbose_name='session_id')),
                ('filename', models.CharField(max_length=200, verbose_name='filename')),
                ('path', models.CharField(max_length=200, verbose_name='path')),
                ('filepath', models.CharField(max_length=200, verbose_name='filepath')),
            ],
        ),
    ]
