# Generated by Django 3.0.3 on 2020-03-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_availablesession_greymattervolume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableSession',
        ),
    ]
