# Generated by Django 3.0.3 on 2020-03-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_availablesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientEntry',
        ),
    ]
