# Generated by Django 3.0.5 on 2020-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreyMatterVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='session_id')),
                ('participant_id', models.CharField(max_length=100, verbose_name='participant_id')),
                ('filename', models.CharField(max_length=200, verbose_name='filename')),
                ('path', models.CharField(max_length=200, verbose_name='path')),
                ('filepath', models.CharField(max_length=200, verbose_name='filepath')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PatientResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=5, verbose_name='Patient ID')),
                ('predicted_age', models.CharField(max_length=50, verbose_name='Predicted Age')),
                ('predicted_sex', models.CharField(max_length=50, verbose_name='Predicted Sex')),
                ('predicted_premature', models.CharField(max_length=200, verbose_name='Predicted Premature')),
                ('segmented_address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Patient Results',
            },
        ),
        migrations.CreateModel(
            name='SessionDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=100, verbose_name='participant_id')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='session_id')),
                ('gender', models.CharField(max_length=100, verbose_name='gender')),
                ('birth_age', models.CharField(max_length=100, verbose_name='birth_age')),
                ('birth_weight', models.CharField(max_length=100, verbose_name='birth_weight')),
                ('singleton', models.CharField(max_length=100, verbose_name='singleton')),
                ('scan_age', models.CharField(max_length=50, verbose_name='scan_age')),
                ('scan_number', models.CharField(max_length=50, verbose_name='scan_number')),
                ('radiology_score', models.CharField(max_length=200, verbose_name='radiology_score')),
                ('sedation', models.CharField(max_length=200, verbose_name='sedation')),
            ],
            options={
                'verbose_name_plural': 'Session Database',
            },
        ),
    ]
