# Generated by Django 3.0.5 on 2020-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SessionDatabase',
            fields=[
                ('participant_id', models.CharField(max_length=100, verbose_name='participant_id')),
                ('session_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='session_id')),
                ('gender', models.CharField(max_length=100, verbose_name='gender')),
                ('birth_age', models.FloatField(verbose_name='birth_age')),
                ('birth_weight', models.FloatField(verbose_name='birth_weight')),
                ('singleton', models.CharField(max_length=100, verbose_name='singleton')),
                ('scan_age', models.FloatField(verbose_name='scan_age')),
                ('scan_number', models.IntegerField(verbose_name='scan_number')),
                ('radiology_score', models.CharField(max_length=200, verbose_name='radiology_score')),
                ('sedation', models.CharField(max_length=200, verbose_name='sedation')),
                ('mri_file', models.FileField(default='', upload_to='uploads/data/mris/', verbose_name='MRI file path')),
                ('surface_file', models.FileField(default='', upload_to='uploads/data/vtps/', verbose_name='Surface file path')),
            ],
            options={
                'verbose_name_plural': 'Session Database',
                'ordering': ['-session_id'],
            },
        ),
        migrations.CreateModel(
            name='UploadedSessionDatabase',
            fields=[
                ('participant_id', models.CharField(max_length=100, verbose_name='participant_id')),
                ('session_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='session_id')),
                ('gender', models.CharField(max_length=100, verbose_name='gender')),
                ('birth_age', models.FloatField(verbose_name='birth_age')),
                ('birth_weight', models.FloatField(verbose_name='birth_weight')),
                ('singleton', models.CharField(max_length=100, verbose_name='singleton')),
                ('scan_age', models.FloatField(verbose_name='scan_age')),
                ('scan_number', models.IntegerField(verbose_name='scan_number')),
                ('radiology_score', models.CharField(max_length=200, verbose_name='radiology_score')),
                ('sedation', models.CharField(max_length=200, verbose_name='sedation')),
                ('mri_file', models.FileField(default='', upload_to='uploads/data/mris/', verbose_name='MRI file path')),
                ('surface_file', models.FileField(default='', upload_to='uploads/data/vtps/', verbose_name='Surface file path')),
            ],
            options={
                'verbose_name_plural': 'Uploaded Session Database',
                'ordering': ['-session_id'],
            },
        ),
    ]
