# Generated by Django 3.0.5 on 2020-04-22 20:24

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondatabase',
            name='session_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[main.models.validate_session_id_is_unique], verbose_name='session_id'),
        ),
        migrations.AlterField(
            model_name='uploadedsessiondatabase',
            name='session_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[main.models.validate_session_id_is_unique], verbose_name='session_id'),
        ),
    ]
